-- Seed data extracted from the Google Sheet

INSERT INTO contents (
    id, type, l1, l2, l3_label, title, lead_text, body_text,
    l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en,
    l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw,
    image1, homepage
) VALUES 
(
    '02-02-00-0001', 'sheet_import',
    '知る', '飯綱町について', '地理とアクセス', '里山の風景が残りつつ、都市からのアクセスも良好な「ちょうどいい田舎」。', NULL, '長野県北部に位置する飯綱町は、標高500〜900mの丘陵地帯に広がる、人口およそ１万人の小さな町です。北信五岳を望む古き良き里山の風景が魅力で、昼夜の寒暖差に恵まれた気候はりんご栽培に適しており、豊かな自然と暮らしやすさを両立しています。隣接する長野市や中野市へは車で20〜30分と通勤圏内で、生活利便性も確保されています。東京からは新幹線と在来線で約2時間、大阪からも約4時間でアクセス可能。「ちょうどいい田舎」として、多くの人々を惹きつけています。',
    'Discover', 'Our Heritage', 'Geography and Access', 'An Ideal Countryside where traditional satoyama landscapes endure, yet offers excellent access to urban centers.', NULL, 'Iizuna Town, located in northern Nagano Prefecture, is a small town with a population of approximately 10,000, spread across hilly terrain at an elevation of 500 to 900 meters. Its charm lies in the timeless satoyama landscapes overlooking the Hokushin Five Mountains. The climate, blessed with significant diurnal temperature variation, is ideal for agriculture, balancing abundant nature with high livability. Neighboring Nagano City and Nakano City are within a 20-30 minute drive, ensuring convenience for daily life and commuting. Access from Tokyo is approximately 2 hours by Shinkansen and local train lines, and about 4 hours from Osaka. As an Ideal Countryside, it attracts many people.',
    '探索', '關於飯綱町', '地理與交通', '保留里山風光，同時擁有便利都市交通的「恰到好處的鄉村」。', NULL, '飯綱町位於長野縣北部，是一座人口約一萬人，座落於海拔500至900公尺丘陵地帶的小鎮。這裡的魅力在於能眺望北信五嶽的古樸里山風光，晝夜溫差大的氣候非常適合農業發展，完美結合了豐饒自然與宜居生活。開車20至30分鐘即可抵達鄰近的長野市與中野市，屬於通勤圈範圍內，生活便利性無虞。從東京搭乘新幹線與在地鐵路約2小時可達，從大阪出發也約4小時即可抵達。作為「恰到好處的鄉村」，吸引了眾多人們前來。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/a6835820-8ee6-013e-065c-0a58a9feac02/iizuna_location.png',
    'https://www.town.iizuna.nagano.jp/docs/866.html'
),
(
    '02-02-00-0002', 'sheet_import',
    '知る', '飯綱町について', 'これまでの歩み', '伝統と挑戦が息づくりんごのまち。', NULL, '飯綱町は2005年に、旧牟礼村と旧三水村が合併して誕生しました。町の基幹産業の一つであるりんご栽培は、明治時代にはじまり、大正期の農業団体設立や昭和初期の桑畑転換を経て発展。昭和40年代には旧三水村が全国有数の生産地として「日本一のりんご村」と呼ばれました。現在も町内各地でりんご栽培が続けられており、海外品種を含めた50以上の多種多様なりんごが栽培されています。また、北国街道の宿場「牟礼宿」として栄えた歴史や、郷土料理「やたら」をはじめとする暮らしに根付いた伝統文化を守りながら、閉校した小学校を活用して、複合施設「いいづなコネクトWEST」「いいづなコネクトEAST」を開設するなど、新しいことにも挑戦し続けている町です。',
    'Discover', 'Our Heritage', 'Our Journey So Far', 'An apple town where tradition and innovation thrive.', NULL, 'Iizuna Town was formed in 2005 through the merger of the former Mure Village and former Samizu Village. Apple cultivation, one of the town''s core industries, began in the Meiji era and developed through the establishment of agricultural organizations in the Taisho period and the conversion of mulberry fields in the early Showa period. In the Showa 40s (1960s), the former Samizu Village was renowned as Japan''s premier apple-producing village. Today, apple cultivation continues throughout the town, with over 50 diverse varieties, including foreign varieties, being grown. While preserving its rich history as Mure-juku, a Post Town on the Hokkoku Kaido, and traditional cultures rooted in daily life, such as the Local Cuisine Yatara, the town also continues to embrace new challenges. This includes the establishment of the multi-purpose complexes Iizuna Connect WEST and Iizuna Connect EAST, utilizing former elementary school buildings.',
    '探索', '關於飯綱町', '歷史沿革', '傳統與創新並存的蘋果小镇。', NULL, '飯綱町於2005年由舊牟禮村與舊三水村合併而成。蘋果栽培是本町的基幹產業之一，始於明治時代，歷經大正時期農業團體的成立以及昭和初期桑田轉作，逐步發展。昭和40年代（1960年代），舊三水村曾以全國首屈一指的蘋果產地之姿，被譽為「日本第一的蘋果村」。如今，町內各地仍持續進行蘋果栽培，種植著包含海外品種在內，超過50種多樣化的蘋果。此外，本町在守護北國街道宿場「牟禮宿」的繁榮歷史，以及以在地特色料理Yatara為首，根植於生活的傳統文化的同時，也持續挑戰新事物，例如活用廢校小學，開設了複合設施「飯綱Connect WEST」與「飯綱Connect EAST」。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/c2823380-8eef-013e-f645-0a58a9feac02/top_logoContents_sp.jpg',
    'https://www.town.iizuna.nagano.jp/docs/865.html'
),
(
    '02-02-00-0003', 'sheet_import',
    '知る', '飯綱町について', 'りんご栽培に適した気候条件', '昼夜の寒暖差と豊かな自然が、りんごの品質を高める。', NULL, '飯綱町は、標高と、内陸性気候特有の昼夜の寒暖差に恵まれ、りんご栽培に理想的な条件を備えています。日中に生成された糖分が夜間の低温で保持されることで甘みが凝縮し、実がしっかりと引き締まると言われています。加えて、糖度と酸度のバランスも抜群。澄んだ空気や豊富な水源、長い日照時間が、飯綱町ならではのりんごの美味しさを実現し、科学的にも証明されています。',
    'Discover', 'Our Heritage', 'Climate Conditions Suitable for Apple Cultivation', 'Diurnal temperature variation and abundant nature enhance the quality of apples.', NULL, 'Iizuna Town is blessed with ideal conditions for apple cultivation, thanks to its elevation and the significant diurnal temperature variation characteristic of its Inland Climate. It is said that sugars produced during the day are retained by low night temperatures, concentrating the sweetness and firming the fruit. Furthermore, the balance of Sugar Content and Acidity is exceptional. Clear air, abundant water sources, and long hours of sunshine contribute to the unique deliciousness of Iizuna Town''s apples, which has also been scientifically substantiated.',
    '探索', '關於飯綱町', '適合蘋果栽培的氣候條件', '晝夜溫差與豐饒自然，提升蘋果品質。', NULL, '飯綱町擁有得天獨厚的海拔條件，以及內陸性氣候特有的晝夜溫差，具備了蘋果栽培的理想環境。據說，白天生成的糖分在夜間低溫下得以保留，使甜味濃縮，果實也更加緊實。此外，糖度與酸度的平衡也極為出色。清澈的空氣、豐沛的水源以及充足的日照時間，共同造就了飯綱町獨有的蘋果美味，這也已獲得科學驗證。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/f2837410-8f03-013e-e63d-0a58a9feac02/photo-intermediate.jpg',
    'https://1127.info/about/'
),
(
    '02-02-00-0004', 'sheet_import',
    '知る', '飯綱町について', 'りんごを核に描く未来戦略', '「りんご」を核に、地域資源を磨き上げる独自のまちづくりを推進。', NULL, '飯綱町は、「日本一のりんごの町」を掲げ、りんごを核とした地域戦略「輝く農山村地域創造推進プロジェクト」を展開しています。抜群の糖度と酸度のバランスや食感の科学的証明を生かした高付加価値化、未利用資源の活用、そして観光や教育と結びつけた関係人口づくりなど、りんごを中心に多方面へ波及する取り組みが進行中です。農業だけに留まらず、健康・文化・働き方までを含めた持続可能な地域モデルをかたちづくり、「ちょうどいい田舎」から新たな未来を発信しています。',
    'Discover', 'Our Heritage', 'Crafting a Future Strategy with Apples at its Core', 'Promoting unique town development that refines local resources, with apples as its central pillar.', NULL, 'Iizuna Town champions itself as ''Japan''s premier apple town,'' driving a regional strategy centered on apples, known as the ''Shining Agricultural and Mountain Village Creation Promotion Project.'' This initiative encompasses a wide range of efforts radiating from apples, including adding high value by leveraging the Scientific Substantiation of their excellent balance of sugar content and acidity, and unique Texture; utilizing untapped resources; and fostering a Relationship Population through tourism and education. Beyond agriculture, the town is shaping a Sustainable regional model that embraces health, culture, and diverse working styles, broadcasting a new future from its Ideal Countryside.',
    '探索', '關於飯綱町', '以蘋果為核心描繪的未來戰略', '以「蘋果」為核心，推動獨特的城鎮建設，精進地方資源。', NULL, '飯綱町以「日本首屈一指的蘋果小镇」為目標，推動以蘋果為核心的區域戰略「閃耀農山村地域創造推進計畫」。這項計畫以蘋果卓越的糖酸比與口感的科學驗證為基礎，致力於提升附加價值、活化未利用資源，並透過結合觀光與教育來創造「關係人口」，以蘋果為中心，多面向的措施正持續推展。這不僅限於農業，更涵蓋健康、文化、生活方式等層面，旨在建構永續的區域模式，從「恰到好處的鄉村」向世界發送嶄新的未來。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/3bb6c340-8d6a-013e-ae9b-0a58a9feac02/20231120_mitsudon-11.jpg',
    'https://www.town.iizuna.nagano.jp/docs/10947.html'
),
(
    '02-03-00-0005', 'sheet_import',
    '知る', 'いいづなりんごの特徴', '多様な品種', '季節ごとに多彩な味が楽しめる、50種以上のりんごの宝庫。', NULL, '町内では「ふじ」「つがる」といった定番に加え、長野県生まれの「秋映」「シナノスイート」「シナノゴールド」「シナノリップ」など、さまざまな品種が栽培されています。希少な和りんごの「高坂りんご」や調理や加工に向く海外品種、さらには赤果肉りんごまで、その品種の数は50種以上。昼夜の寒暖差に恵まれた気候と豊かな水源が、多彩な味わいと高い品質を支えています。飯綱町のりんごシーズンは「ブラムリー」を皮切りに８月にスタートします。季節ごとに異なる味が楽しめるのも、多種多様なな品種を育むこの地域ならではの魅力です。',
    'Discover', 'Flavor & Science', 'Diverse Varieties', 'A treasure trove of over 50 apple varieties, offering different tastes each season.', NULL, 'In Iizuna Town, in addition to classic varieties like Fuji Apple, Tsugaru, and Orin, a rich array of unique varieties developed in Nagano Prefecture, such as Akibae, Shinano Sweet, and Shinano Gold, are cultivated. The town boasts over 50 varieties, including the rare Native Japanese Apple ''Kosaka Apple'', foreign varieties suitable for Cooking Apple, and even Red-fleshed Apples. The climate, blessed with significant Diurnal Temperature Variation, and abundant water sources support this diverse range of flavors and high quality. The ability to enjoy different tastes each season is a unique charm of this region, which cultivates such a wide variety of apples.',
    '探索', '飯綱蘋果的特徵', '多樣的蘋果品種', '超過50種蘋果的寶庫，每個季節都能品嚐到不同風味。', NULL, '飯綱町內除了「富士蘋果 (Fuji)」、「津輕蘋果 (Tsugaru)」、「王林蘋果 (Orin)」等經典品種外，還栽培著長野縣原生的「秋映蘋果 (Akiho)」、「信濃甜蘋果 (Shinano Sweet)」、「信濃黃金蘋果 (Shinano Gold)」等獨具特色的品種。從稀有的日本原生蘋果「高坂蘋果 (Kosaka Apple)」，到適合料理的西洋蘋果品種，乃至於紅肉蘋果，其數量多達50種以上。得天獨厚的晝夜溫差氣候與豐沛的水源，支持著蘋果多樣的風味與高品質。每個季節都能品嚐到不同風味，正是這個孕育多樣品種的地區獨有的魅力。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/8ae3ad00-8d6a-013e-bcd3-0a58a9feac02/IMG_2898.jpg',
    NULL
),
(
    '02-03-00-0006', 'sheet_import',
    '知る', 'いいづなりんごの特徴', '高い栄養価', '食べるほどにうれしい、栄養と機能性が詰まった果実の魅力。', NULL, '「1日1個のりんごで医者いらず」（An apple a day keeps the doctor away／イギリス・ウェールズ地方に伝わることわざ）と言われるほど、りんごは食物繊維やカリウム、ビタミン類を豊富に含み、腸内環境を整えたり生活習慣病の予防に役立つ果物として知られています。特に希少な和りんごの「高坂りんご」は注目されており、老化を抑える抗酸化作用を持つプロシアニジンが「ふじ」の約10倍含まれることが研究で確認されています。さらに内臓脂肪減少効果も期待され、加工品開発にも繋がっています。そのほか赤果肉りんごに含まれるアントシアニンなど、品種ごとに機能性研究が進められています。',
    'Discover', 'Flavor & Science', 'High Nutritional Value', 'The appeal of fruit packed with nutrition and Functional Benefits, a delight with every bite.', NULL, 'Apples are known as fruits rich in dietary fiber, potassium, and vitamins, helping to regulate the intestinal environment and prevent lifestyle-related diseases. The ancient variety from Iizuna Town, ''Kosaka Apple'', is particularly noteworthy; research has confirmed it contains approximately 10 times more Procyanidin, an Antioxidant Effect that suppresses aging, than the Fuji Apple. Furthermore, its potential for Visceral Fat reduction is also anticipated, leading to the development of processed products. Beyond this, Functional Benefits research is progressing for various varieties, such as the Anthocyanin found in Red-fleshed Apples.',
    '探索', '飯綱蘋果的特徵', '高營養價值', '富含營養與機能性保健功效的果實魅力，越吃越健康。', NULL, '蘋果富含膳食纖維、鉀、維生素等，是眾所周知有助於調理腸道環境、預防生活習慣病的果實。特別是飯綱町的古老品種「高坂蘋果 (Kosaka Apple)」備受矚目，研究證實其所含的「原花青素」，具有抑制老化的「抗氧化作用」，含量約為「富士蘋果 (Fuji)」的10倍。此外，它還被期待具有內臟脂肪減少的功效，並已應用於加工品的開發。除此之外，針對紅肉蘋果所含的「花青素」等，各類品種的機能性保健功效研究也正持續進行中。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/b4170770-8d6a-013e-bcf1-0a58a9feac02/sunfuji_mitsu-2.jpg',
    NULL
),
(
    '02-03-00-0007', 'sheet_import',
    '知る', 'いいづなりんごの特徴', 'シャキシャキの食感', '歯ごたえの良さは数値でも証明', NULL, '飯綱町産のりんごの大きな魅力は、ひと口かじった瞬間に伝わる「シャキシャキ」とした歯ごたえです。この食感は、長野県工業技術総合センターによる測定で破断強度が高いことが示され、科学的にも証明されています。背景には、昼夜の寒暖差が大きい内陸性気候があり、これによって実がしっかりと引き締まり、特有の硬さが生まれます。また、栽培環境と品種特性が合わさることで独自の歯ごたえが育まれています。味とともにこの食感にもぜひご注目ください。',
    'Discover', 'Flavor & Science', 'Crisp Texture', 'The excellent crunchiness of Iizuna apples is a scientifically proven characteristic.', NULL, 'A major appeal of Iizuna Town''s apples is the satisfying crispness that greets you with every bite. This texture is scientifically substantiated, with measurements by the Nagano Prefecture General Industrial Technology Center showing high fracture strength. This unique firmness is attributed to Iizuna''s inland climate, which features significant Diurnal Temperature Variation, causing the fruit to firm up beautifully. Depending on the variety, you can enjoy a refreshing crispness, as found in Shinano Lip and Shinano Red, where the cultivation environment and varietal characteristics combine to foster this distinctive texture.',
    '探索', '飯綱蘋果的特徵', '爽脆的口感', '絕佳咬勁經科學驗證，是飯綱蘋果的鮮明特色。', NULL, '飯綱町蘋果的巨大魅力，在於一口咬下瞬間感受到的「爽脆」咬勁。這種口感經長野縣工業技術綜合中心 (Nagano Prefecture General Industrial Technology Center) 測量顯示其斷裂強度高，亦獲得科學驗證。其背後原因在於晝夜溫差大的內陸性氣候，使果實緊實，產生獨特的硬度。部分品種如信濃麗 (Shinano Lip) 和信濃紅 (Shinano Red) 則能享受清爽的口感，栽培環境與品種特性相結合，共同孕育出獨特的咬勁。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/02d66ae0-8d6a-013e-0556-0a58a9feac02/20230118_apple_cut-3.jpg',
    NULL
),
(
    '02-03-00-0008', 'sheet_import',
    '知る', 'いいづなりんごの特徴', '甘みと酸味のバランス', '絶妙な糖酸バランスが生み出す飯綱町産りんごの深い味わい', NULL, 'りんごの美味しさを大きく左右するのが、甘みと酸味の調和です。長野県工業技術総合センターの調査では、飯綱町産の「ふじ」が、他産地のりんごに比べ、糖度・酸度ともに高い水準を記録し、さらには一般的に美味しいとされる糖酸比（甘味と酸味のバランス）30〜40に近い数値を示しました。甘さと酸っぱさが絶妙に重なり合うことで、豊かなコクと爽やかさが生まれ、多くの人に愛される味わいとなっています。',
    'Discover', 'Flavor & Science', 'Balance of Sweetness and Acidity', 'An exquisite sugar-acid balance creates the deep, rich flavor of Iizuna apples.', NULL, 'The harmony of sweetness and acidity significantly influences an apple''s deliciousness. A study by the Nagano Prefecture General Industrial Technology Center revealed that Iizuna-grown Fuji Apples recorded high levels of both Sugar Content and acidity compared to apples from other regions. Furthermore, they exhibited a Sugar-Acid Ratio close to the generally preferred range of 30-40. This exquisite interplay of sweetness and tartness creates a rich depth of flavor and refreshing quality, making them beloved by many.',
    '探索', '飯綱蘋果的特徵', '甜度與酸度的完美平衡', '絕妙的糖酸比，造就蘋果深邃的風味。', NULL, '蘋果美味與否，甜度與酸度的和諧是關鍵。長野縣工業技術綜合中心 (Nagano Prefecture General Industrial Technology Center) 的調查顯示，飯綱町產的「富士蘋果 (Fuji)」相較於其他產地的蘋果，在糖度與酸度上均達到高水準。此外，其糖酸比（甜味與酸味的平衡）也接近一般公認美味的30至40之間。甜與酸的絕妙交織，創造出豐富的濃郁風味與清爽感，成為深受大眾喜愛的滋味。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/cd850820-8d6a-013e-c3bf-0a58a9feac02/%E3%83%95%E3%82%99%E3%83%A9%E3%83%A0%E3%83%AA%E3%83%BC_5.jpg',
    NULL
),
(
    '02-03-00-0009', 'sheet_import',
    '知る', 'いいづなりんごの特徴', '栽培方法の特徴', '圃場の条件にあわせた栽培手法でりんご生産を守る', NULL, '町内では大きく分けて「普通（丸葉【まるば】）栽培」と「わい化（わいか）栽培」という２つの栽培方法でりんごが生産されています。普通栽培は、根がしっかり張る大きくて樹を育てて、実をならせる伝統的な栽培方法で、病気や寒さに強いのが特長です。町内には樹齢3～40年を越える木が現役で頑張っている畑も少なくありません。「古い木のほうがおいしいりんごがとれる」という声もあるくらい。一方、わい化栽培は、1本1本の木をコンパクト仕立てて、1本の木により多くの実をならせる方法で、苗を植えてから出荷できるりんごが収穫できるようになるまでが普通栽培よりも格段に速く、作業もしやすくなります。飯綱町では畑ごとの条件や農家の工夫によって両方を組み合わせることで、味わいの良さと安定した収穫を両立させています。',
    'Discover', 'Flavor & Science', 'Distinctive Cultivation Methods', 'Apple farmers employ innovative Tree Training methods to achieve both deliciousness and cultivation efficiency.', NULL, 'Apple orchards primarily utilize two cultivation methods: Standard Cultivation and Dwarfing Cultivation. Standard Cultivation involves traditional trees with deep, strong root systems that can be grown for many years, known for their resistance to disease and cold. Dwarfing Cultivation, on the other hand, involves training smaller trees planted at high density, allowing for earlier harvests and easier management. In Iizuna Town, farmers combine both methods, adapting to specific field conditions and employing their ingenuity to ensure both superior flavor and stable yields.',
    '探索', '飯綱蘋果的特徵', '栽培方法的特色', '蘋果農民巧妙運用樹型培育技術，兼顧美味與栽種便利性。', NULL, '蘋果園主要有兩種栽培方式：「丸葉 (Maruba)」和「矮化栽培 (Waika)」。丸葉 (Maruba) 是一種根系穩固、可長期培育的傳統樹型，特點是抗病耐寒。而矮化栽培 (Waika) 則是將樹木培育得較小，以高密度種植的方式，能提早收穫並方便作業。飯綱町的農民會根據各個果園的條件和自身經驗，將這兩種方法結合運用，以實現絕佳風味與穩定收成。',
    'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/0c9c9c80-8ef3-013e-1b1b-0a58a9feac02/__1.jpg',
    NULL
);


-- Content added from latest user prompt
INSERT OR REPLACE INTO contents (id, type, l1, l2, l3_label, title, lead_text, body_text, l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en, l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw, image1, image2, image3, image4, image5, image6, homepage, related1_url, related1_title, related2_url, related2_title, ec_site, sns_instagram, sns_facebook, sns_x, sns_line, sns_tiktok, address, contact_form_url, contact_email, contact_phone, remarks, download_url, business_days, business_start, business_end, closed_days, business_remarks, start_date, end_date, start_time, end_time, fee, belongings, target_audience, organizer_name, organizer_contact, application_method, venue_remarks) VALUES
('02-02-00-0001', 'manual', '知る', '飯綱町について', NULL, '地理とアクセス', '里山の風景が残りつつ、都市からのアクセスも良好な「ちょうどいい田舎」。', '長野県北部に位置する飯綱町は、標高500〜900mの丘陵地帯に広がる、人口およそ１万人の小さな町です。北信五岳を望む古き良き里山の風景が魅力で、昼夜の寒暖差に恵まれた気候はりんご栽培に適しており、豊かな自然と暮らしやすさを両立しています。隣接する長野市や中野市へは車で20〜30分と通勤圏内で、生活利便性も確保されています。東京からは新幹線と在来線で約2時間、大阪からも約4時間でアクセス可能。「ちょうどいい田舎」として、多くの人々を惹きつけています。', 'Discover', 'Our Heritage', NULL, 'Geography and Access', 'An Ideal Countryside where traditional satoyama landscapes endure, yet offers excellent access to urban centers.', 'Iizuna Town, located in northern Nagano Prefecture, is a small town with a population of approximately 10,000, spread across hilly terrain at an elevation of 500 to 900 meters. Its charm lies in the timeless satoyama landscapes overlooking the Hokushin Five Mountains. The climate, blessed with significant diurnal temperature variation, is ideal for agriculture, balancing abundant nature with high livability. Neighboring Nagano City and Nakano City are within a 20-30 minute drive, ensuring convenience for daily life and commuting. Access from Tokyo is approximately 2 hours by Shinkansen and local train lines, and about 4 hours from Osaka. As an Ideal Countryside, it attracts many people.', '探索', '關於飯綱町', NULL, '地理與交通', '保留里山風光，同時擁有便利都市交通的「恰到好處的鄉村」。', '飯綱町位於長野縣北部，是一座人口約一萬人，座落於海拔500至900公尺丘陵地帶的小鎮。這裡的魅力在於能眺望北信五嶽的古樸里山風光，晝夜溫差大的氣候非常適合農業發展，完美結合了豐饒自然與宜居生活。開車20至30分鐘即可抵達鄰近的長野市與中野市，屬於通勤圈範圍內，生活便利性無虞。從東京搭乘新幹線與在地鐵路約2小時可達，從大阪出發也約4小時即可抵達。作為「恰到好處的鄉村」，吸引了眾多人們前來。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/a6835820-8ee6-013e-065c-0a58a9feac02/iizuna_location.png', NULL, NULL, NULL, NULL, NULL, 'https://www.town.iizuna.nagano.jp/docs/866.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-02-00-0002', 'manual', '知る', '飯綱町について', NULL, 'これまでの歩み', '伝統と挑戦が息づくりんごのまち。', '飯綱町は2005年に、旧牟礼村と旧三水村が合併して誕生しました。町の基幹産業の一つであるりんご栽培は、明治時代にはじまり、大正期の農業団体設立や昭和初期の桑畑転換を経て発展。昭和40年代には旧三水村が全国有数の生産地として「日本一のりんご村」と呼ばれました。現在も町内各地でりんご栽培が続けられており、海外品種を含めた50以上の多種多様なりんごが栽培されています。また、北国街道の宿場「牟礼宿」として栄えた歴史や、郷土料理「やたら」をはじめとする暮らしに根付いた伝統文化を守りながら、閉校した小学校を活用して、複合施設「いいづなコネクトWEST」「いいづなコネクトEAST」を開設するなど、新しいことにも挑戦し続けている町です。', 'Discover', 'Our Heritage', NULL, 'Our Journey So Far', 'An apple town where tradition and innovation thrive.', 'Iizuna Town was formed in 2005 through the merger of the former Mure Village and former Samizu Village. Apple cultivation, one of the town''s core industries, began in the Meiji era and developed through the establishment of agricultural organizations in the Taisho period and the conversion of mulberry fields in the early Showa period. In the Showa 40s (1960s), the former Samizu Village was renowned as Japan''s premier apple-producing village. Today, apple cultivation continues throughout the town, with over 50 diverse varieties, including foreign varieties, being grown. While preserving its rich history as Mure-juku, a Post Town on the Hokkoku Kaido, and traditional cultures rooted in daily life, such as the Local Cuisine Yatara, the town also continues to embrace new challenges. This includes the establishment of the multi-purpose complexes Iizuna Connect WEST and Iizuna Connect EAST, utilizing former elementary school buildings.', '探索', '關於飯綱町', NULL, '歷史沿革', '傳統與創新並存的蘋果小镇。', '飯綱町於2005年由舊牟禮村與舊三水村合併而成。蘋果栽培是本町的基幹產業之一，始於明治時代，歷經大正時期農業團體的成立以及昭和初期桑田轉作，逐步發展。昭和40年代（1960年代），舊三水村曾以全國首屈一指的蘋果產地之姿，被譽為「日本第一的蘋果村」。如今，町內各地仍持續進行蘋果栽培，種植著包含海外品種在內，超過50種多樣化的蘋果。此外，本町在守護北國街道宿場「牟禮宿」的繁榮歷史，以及以在地特色料理Yatara為首，根植於生活的傳統文化的同時，也持續挑戰新事物，例如活用廢校小學，開設了複合設施「飯綱Connect WEST」與「飯綱Connect EAST」。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/c2823380-8eef-013e-f645-0a58a9feac02/top_logoContents_sp.jpg', NULL, NULL, NULL, NULL, NULL, 'https://www.town.iizuna.nagano.jp/docs/865.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-02-00-0003', 'manual', '知る', '飯綱町について', NULL, 'りんご栽培に適した気候条件', '昼夜の寒暖差と豊かな自然が、りんごの品質を高める。', '飯綱町は、標高と、内陸性気候特有の昼夜の寒暖差に恵まれ、りんご栽培に理想的な条件を備えています。日中に生成された糖分が夜間の低温で保持されることで甘みが凝縮し、実がしっかりと引き締まると言われています。加えて、糖度と酸度のバランスも抜群。澄んだ空気や豊富な水源、長い日照時間が、飯綱町ならではのりんごの美味しさを実現し、科学的にも証明されています。', 'Discover', 'Our Heritage', NULL, 'Climate Conditions Suitable for Apple Cultivation', 'Diurnal temperature variation and abundant nature enhance the quality of apples.', 'Iizuna Town is blessed with ideal conditions for apple cultivation, thanks to its elevation and the significant diurnal temperature variation characteristic of its Inland Climate. It is said that sugars produced during the day are retained by low night temperatures, concentrating the sweetness and firming the fruit. Furthermore, the balance of Sugar Content and Acidity is exceptional. Clear air, abundant water sources, and long hours of sunshine contribute to the unique deliciousness of Iizuna Town''s apples, which has also been scientifically substantiated.', '探索', '關於飯綱町', NULL, '適合蘋果栽培的氣候條件', '晝夜溫差與豐饒自然，提升蘋果品質。', '飯綱町擁有得天獨厚的海拔條件，以及內陸性氣候特有的晝夜溫差，具備了蘋果栽培的理想環境。據說，白天生成的糖分在夜間低溫下得以保留，使甜味濃縮，果實也更加緊實。此外，糖度與酸度的平衡也極為出色。清澈的空氣、豐沛的水源以及充足的日照時間，共同造就了飯綱町獨有的蘋果美味，這也已獲得科學驗證。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/f2837410-8f03-013e-e63d-0a58a9feac02/photo-intermediate.jpg', NULL, NULL, NULL, NULL, NULL, 'https://1127.info/about/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-02-00-0004', 'manual', '知る', '飯綱町について', NULL, 'りんごを核に描く未来戦略', '「りんご」を核に、地域資源を磨き上げる独自のまちづくりを推進。', '飯綱町は、「日本一のりんごの町」を掲げ、りんごを核とした地域戦略「輝く農山村地域創造推進プロジェクト」を展開しています。抜群の糖度と酸度のバランスや食感の科学的証明を生かした高付加価値化、未利用資源の活用、そして観光や教育と結びつけた関係人口づくりなど、りんごを中心に多方面へ波及する取り組みが進行中です。農業だけに留まらず、健康・文化・働き方までを含めた持続可能な地域モデルをかたちづくり、「ちょうどいい田舎」から新たな未来を発信しています。', 'Discover', 'Our Heritage', NULL, 'Crafting a Future Strategy with Apples at its Core', 'Promoting unique town development that refines local resources, with apples as its central pillar.', 'Iizuna Town champions itself as ''Japan''s premier apple town,'' driving a regional strategy centered on apples, known as the ''Shining Agricultural and Mountain Village Creation Promotion Project.'' This initiative encompasses a wide range of efforts radiating from apples, including adding high value by leveraging the Scientific Substantiation of their excellent balance of sugar content and acidity, and unique Texture; utilizing untapped resources; and fostering a Relationship Population through tourism and education. Beyond agriculture, the town is shaping a Sustainable regional model that embraces health, culture, and diverse working styles, broadcasting a new future from its Ideal Countryside.', '探索', '關於飯綱町', NULL, '以蘋果為核心描繪的未來戰略', '以「蘋果」為核心，推動獨特的城鎮建設，精進地方資源。', '飯綱町以「日本首屈一指的蘋果小镇」為目標，推動以蘋果為核心的區域戰略「閃耀農山村地域創造推進計畫」。這項計畫以蘋果卓越的糖酸比與口感的科學驗證為基礎，致力於提升附加價值、活化未利用資源，並透過結合觀光與教育來創造「關係人口」，以蘋果為中心，多面向的措施正持續推展。這不僅限於農業，更涵蓋健康、文化、生活方式等層面，旨在建構永續的區域模式，從「恰到好處的鄉村」向世界發送嶄新的未來。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/3bb6c340-8d6a-013e-ae9b-0a58a9feac02/20231120_mitsudon-11.jpg', NULL, NULL, NULL, NULL, NULL, 'https://www.town.iizuna.nagano.jp/docs/10947.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-03-00-0005', 'manual', '知る', 'いいづなりんごの特徴', NULL, '多様な品種', '季節ごとに多彩な味が楽しめる、50種以上のりんごの宝庫。', '町内では「ふじ」「つがる」といった定番に加え、長野県生まれの「秋映」「シナノスイート」「シナノゴールド」「シナノリップ」など、さまざまな品種が栽培されています。希少な和りんごの「高坂りんご」や調理や加工に向く海外品種、さらには赤果肉りんごまで、その品種の数は50種以上。昼夜の寒暖差に恵まれた気候と豊かな水源が、多彩な味わいと高い品質を支えています。飯綱町のりんごシーズンは「ブラムリー」を皮切りに８月にスタートします。季節ごとに異なる味が楽しめるのも、多種多様なな品種を育むこの地域ならではの魅力です。', 'Discover', 'Flavor & Science', NULL, 'Diverse Varieties', 'A treasure trove of over 50 apple varieties, offering different tastes each season.', 'In Iizuna Town, in addition to classic varieties like Fuji Apple, Tsugaru, and Orin, a rich array of unique varieties developed in Nagano Prefecture, such as Akibae, Shinano Sweet, and Shinano Gold, are cultivated. The town boasts over 50 varieties, including the rare Native Japanese Apple ''Kosaka Apple'', foreign varieties suitable for Cooking Apple, and even Red-fleshed Apples. The climate, blessed with significant Diurnal Temperature Variation, and abundant water sources support this diverse range of flavors and high quality. The ability to enjoy different tastes each season is a unique charm of this region, which cultivates such a wide variety of apples.', '探索', '飯綱蘋果的特徵', NULL, '多樣的蘋果品種', '超過50種蘋果的寶庫，每個季節都能品嚐到不同風味。', '飯綱町內除了「富士蘋果 (Fuji)」、「津輕蘋果 (Tsugaru)」、「王林蘋果 (Orin)」等經典品種外，還栽培著長野縣原生的「秋映蘋果 (Akiho)」、「信濃甜蘋果 (Shinano Sweet)」、「信濃黃金蘋果 (Shinano Gold)」等獨具特色的品種。從稀有的日本原生蘋果「高坂蘋果 (Kosaka Apple)」，到適合料理的西洋蘋果品種，乃至於紅肉蘋果，其數量多達50種以上。得天獨厚的晝夜溫差氣候與豐沛的水源，支持著蘋果多樣的風味與高品質。每個季節都能品嚐到不同風味，正是這個孕育多樣品種的地區獨有的魅力。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/8ae3ad00-8d6a-013e-bcd3-0a58a9feac02/IMG_2898.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO contents (id, type, l1, l2, l3_label, title, lead_text, body_text, l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en, l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw, image1, image2, image3, image4, image5, image6, homepage, related1_url, related1_title, related2_url, related2_title, ec_site, sns_instagram, sns_facebook, sns_x, sns_line, sns_tiktok, address, contact_form_url, contact_email, contact_phone, remarks, download_url, business_days, business_start, business_end, closed_days, business_remarks, start_date, end_date, start_time, end_time, fee, belongings, target_audience, organizer_name, organizer_contact, application_method, venue_remarks) VALUES
('02-04-04-0001', 'manual', '知る', '栽培されている品種', '町指定天然記念物', '高坂林檎', '幻の和りんご、小さな実が鈴なりに実る', '明治時代に西洋りんごが日本に伝わる以前に中国から伝来したとされる在来種。品種名は、産地だった飯綱町高坂（こうさか）の地名に由来。昭和末期に絶滅寸前となったが町内有志農家による保存活動で命脈をつなぎ、町内原木2本が町の天然記念物に指定されている。全国的にも在来種の現存はとても珍しい。味は渋くて、酸っぱいため、生食はできないが、近年、ポリフェノールの一種である「プロシアニジン」を豊富に含んでいることがわかり、ジュースやシードルへの加工用として注目されている。収穫は８月頃。', 'Discover', 'Apple Varieties', 'Heirloom & Monuments', 'Kosaka Apple', 'An elusive native Japanese apple, bearing small fruits in abundance.', 'This native variety is believed to have been introduced from China before the arrival of Western Apples. It was on the verge of extinction in the late Showa era, but preservation efforts kept it alive, and two original trees in the town have been designated as natural monuments. Recently, it has gained attention as an ingredient for Cider.', '探索', '蘋果品種', '天然紀念物品種', '高坂苹果', '夢幻般的日本原生蘋果，小巧果實纍纍', '據傳是在西洋蘋果傳入日本之前，從中國傳來的日本原生品種。在昭和末期曾瀕臨絕種，但透過保存活動得以延續命脈，町內有兩棵原木被指定為天然紀念物。近年來，作為蘋果酒 (Cider) 的原料而備受矚目。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E9%AB%98%E5%9D%82%E6%9E%97%E6%AA%8E.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-05-0022', 'manual', '知る', '栽培されている品種', '定番品種', 'サンつがる', '9月上旬に出回る甘み豊かな早生種', '果汁が多く甘さが強いのが特徴。果肉は柔らかめで酸味は少なく食べやすい。早い時期に楽しめるため人気の高い品種です。', 'Discover', 'Apple Varieties', 'Classic Varieties', 'Sun Tsugaru', 'A richly sweet, early-ripening variety available in early September.', 'Known for its abundant juice and intense sweetness, the Sun Tsugaru apple features tender flesh with low acidity, making it exceptionally easy to enjoy. Its early availability makes it a highly popular choice among apple enthusiasts.', '探索', '蘋果品種', '經典品種', '太阳津轻', '9月上旬上市的甜美早生品種', '果汁豐富，甜度高是其特色。果肉柔軟，酸度較低，易於食用。由於上市時間早，是很受歡迎的品種。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B5%E3%83%B3%E3%81%A4%E3%81%8C%E3%82%8B.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-05-0023', 'manual', '知る', '栽培されている品種', '定番品種', '紅玉', '強い酸味と多汁さで加工に最適', '10月中旬が旬。鮮やかな赤色と酸味の強さが特徴で、アップルパイなどお菓子用に根強い人気があります。', 'Discover', 'Apple Varieties', 'Classic Varieties', 'Jonathan', 'Ideal for processing, characterized by strong acidity and juiciness.', 'Peaking in mid-October, the Jonathan apple is distinguished by its vibrant red color and pronounced tartness. This makes it a long-standing favorite for baking, especially for delicious Apple Pies and other sweets.', '探索', '蘋果品種', '經典品種', '紅玉', '酸度強且多汁，最適合加工', '10月中旬為盛產期。鮮豔的紅色與強烈的酸度是其特色，作為蘋果派等甜點的原料，擁有居高不下的人氣。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E7%B4%85%E7%8E%89.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-05-0025', 'manual', '知る', '栽培されている品種', '定番品種', '王林', '黄緑色の果皮と強い甘みが特徴', '酸味が少なく、芳醇な香りとパリッとした食感が楽しめる。保存性が高く冬まで美味しさを保ち、甘党に好まれるりんごです。', 'Discover', 'Apple Varieties', 'Classic Varieties', 'Orin', 'Features yellowish-green skin and intense sweetness.', 'The Orin apple offers a delightful combination of low acidity, a rich aroma, and a crisp texture. Renowned for its excellent shelf life, it retains its delicious flavor well into winter, making it a beloved choice for those with a sweet tooth.', '探索', '蘋果品種', '經典品種', '王林', '黃綠色果皮與濃郁甜味是其特色', '酸度較低，可享受其芳醇香氣與清脆口感。保存性高，能將美味維持至冬季，是嗜甜者喜愛的蘋果。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E7%8E%8B%E6%9E%97.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-05-0027', 'manual', '知る', '栽培されている品種', '定番品種', 'サンふじ', '甘み・酸味・食感が揃った世界的人気品種', '日本を代表する品種で、11月中旬が旬。無袋栽培のサンふじは蜜入りで特に甘く、シャキッとした食感も魅力。長期保存性も高く世界各地で栽培されています。', 'Discover', 'Apple Varieties', 'Classic Varieties', 'Sun Fuji', 'A globally popular variety with a perfect balance of sweetness, acidity, and texture.', 'As Japan''s most iconic apple, Sun Fuji is typically harvested in mid-November. The bagless cultivation method enhances its honeycore and sweetness, complemented by a delightful crisp texture. Its superior storability has led to its cultivation worldwide.', '探索', '蘋果品種', '經典品種', '太阳富士', '甜度、酸度、口感兼備的全球人氣品種', '作為日本代表性的品種，11月中旬為產季。無袋栽培的陽光富士特別香甜且帶有果蜜，清脆的口感也是其魅力所在。保存性高，全球各地皆有栽培。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B5%E3%83%B3%E3%81%B5%E3%81%98.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0009', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノリップ', '夏りんごの新定番！？ジューシーで香り豊か', '「千秋」と「シナノレッド」の交配種で、歯ごたえと果汁の多さが特徴。新しい長野県生まれの注目品種です。ポスト夏りんごの定番「つがる」！？収穫は8月中旬～下旬。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Lip', 'A new summer apple variety, juicy and aromatic.', 'Its season is from mid to late August. This new and noteworthy variety, born in Nagano Prefecture, is a cross between Chiaki and Shinano Red, characterized by its crunchiness and abundant juice.', '探索', '蘋果品種', '長野原創品種', '信浓唇', '新品種夏蘋果，多汁且香氣濃郁', '8月中旬至下旬為產季。是千秋 (Senko) 和信濃紅 (Shinano Red) 的雜交品種，特點是咬勁十足且果汁豐富。是長野縣新培育的矚目品種。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%83%AA%E3%83%83%E3%83%97.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0010', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノピッコロ', '名前も見た目もかわいい新品種', '「ゴールデンデリシャス」と「あかね」をかけ合わせた長野県生まれの新品種です。果肉がしっかりしていて、小さいけれど食べごたえがあります。ちなみに「ピッコロ」は、イタリア語で「小さい」という意味。収穫は9月中旬～下旬。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Piccolo', 'A charming new variety, delightful in both name and appearance.', 'This new variety, born in Nagano Prefecture, is a cross between ''Golden Delicious'' and ''Akane''. It has firm flesh and, despite its small size, offers a satisfying bite. Incidentally, ''Piccolo'' means ''small'' in Italian. Harvest is from mid to late September.', '探索', '蘋果品種', '長野原創品種', '信濃笛 (Shinano Piccolo)', '名字與外型皆可愛的新品種', '這是長野縣培育出的新品種，由「金冠蘋果 (Golden Delicious)」與「秋映 (Akane)」雜交而成。果肉紮實，雖然小巧卻口感十足。順帶一提，「Piccolo」在義大利語中意為「小」。採收期為9月中旬至下旬。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%83%94%E3%83%83%E3%82%B3%E3%83%AD.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO contents (id, type, l1, l2, l3_label, title, lead_text, body_text, l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en, l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw, image1, image2, image3, image4, image5, image6, homepage, related1_url, related1_title, related2_url, related2_title, ec_site, sns_instagram, sns_facebook, sns_x, sns_line, sns_tiktok, address, contact_form_url, contact_email, contact_phone, remarks, download_url, business_days, business_start, business_end, closed_days, business_remarks, start_date, end_date, start_time, end_time, fee, belongings, target_audience, organizer_name, organizer_contact, application_method, venue_remarks) VALUES
('02-04-06-0012', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', '秋映（あきばえ）', '濃赤の美しいりんご、甘酸っぱさが絶妙', '「千秋」と「つがる」を交配。濃い赤色の果皮は美しく、甘みと酸味のバランスが抜群。10月上旬に出回る信州の秋の象徴です。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Akibae', 'Beautiful dark red apple with an exquisite sweet-tart balance.', 'Created by crossing ''Senshu'' and ''Tsugaru'', this variety boasts stunning dark red skin and a perfect balance of sweetness and acidity. Arriving in early October, it is a quintessential symbol of autumn in Shinshu.', '探索', '蘋果品種', '長野原創品種', '秋映', '深紅美麗的蘋果，酸甜滋味絕佳', '「千秋 (Senko)」與「津輕 (Tsugaru)」的雜交品種。深紅色的果皮十分美麗，甜味與酸味的平衡極佳。10月上旬上市，是信州秋季的象徵。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E7%A7%8B%E6%98%A0.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0013', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノスイート', 'やさしい甘みとサクサク食感が大人気', '「ふじ」と「つがる」の交配種。酸味が少なく、やさしい甘さが口いっぱいに広がります。10月中旬が食べ頃の子どもからお年寄りにまで愛される「りんご３兄弟」の次男？次女？', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Sweet', 'Widely loved for its gentle sweetness and crispy texture.', 'A crossbreed of ''Fuji'' and ''Tsugaru'', this apple features low acidity, allowing its gentle sweetness to fill the mouth. Peaking in mid-October, it is cherished by people of all ages, affectionately known as the ''middle sibling'' of the ''Three Shinano Siblings.''', '探索', '蘋果品種', '長野原創品種', '信浓甜', '溫和的甜味與酥脆口感深受喜愛', '「富士蘋果 (Fuji)」與「津輕蘋果 (Tsugaru)」的雜交種。幾乎不酸，柔和的甜味能在口中擴散。10月中旬為最佳品嚐期，是深受各年齡層喜愛的「蘋果三兄弟」中的老二。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%82%B9%E3%82%A4%E3%83%BC%E3%83%88.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0015', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノゴールド', '黄金色に輝くパリッと爽快なりんご', '「ゴールデンデリシャス」と「千秋」の交配種。黄色い果皮で、酸味と甘みのメリハリが特徴。10月下旬から楽しめ、日持ちも優れています。ヨーロッパを中心に世界中で「Yellow」（イエロー）という名で販売されています。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Gold', 'A crisp and refreshing apple shining in a radiant golden hue.', 'A cross between ''Golden Delicious'' and ''Senshu'', this variety is characterized by its yellow skin and a lively contrast of sweetness and tartness. Available from late October, it boasts excellent shelf life and is renowned globally, particularly in Europe, under the name ''Yellow.''', '探索', '蘋果品種', '長野原創品種', '信浓黄', '閃耀金黃色的清脆爽口蘋果', '「金冠蘋果 (Golden Delicious)」與「千秋蘋果 (Senko)」的雜交品種。黃色的果皮，酸味與甜味分明。10月下旬起可享用，保存期長。在歐洲等地以「Yellow」為名廣泛銷售。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0016', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノホッペ', '果肉まで甘みが浸透！蜜入りが期待できる新品種', '「あかね」と「ふじ」の交配種。10月下旬～11月上旬に収穫される、濃い赤色の外観が美しいりんごです。「ふじ」のように蜜が入りやすく、濃厚な甘さと豊かな香りが特徴で、近年人気急上昇中です。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Hoppe', 'Sweetness infused down to the flesh! A new variety expected to have honeycore.', 'A cross between ''Akane'' and ''Fuji'', this stunning dark red apple is harvested from late October to early November. Like ''Fuji'', it is prone to developing honeycore and features rich sweetness and a fragrant aroma, driving its rapidly growing popularity.', '探索', '蘋果品種', '長野原創品種', '信浓红颊', '甜味滲透果肉！帶有果蜜的期待新品種', '「秋映 (Akane)」與「富士蘋果 (Fuji)」的交配種。收成期約在10月下旬至11月上旬，外觀呈美麗的深紅色。與「富士蘋果 (Fuji)」一樣容易結蜜，擁有濃郁的甜味與豐富的香氣，近年人氣攀升。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%83%9B%E3%83%83%E3%83%9A.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0017', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノプッチ', 'お弁当にぴったり！丸かじりサイズの極小りんご', '「さんさ」と「つがる」を交配した極小サイズのりんごです。果皮が薄く、皮ごと丸かじりできるのが特徴。酸味は控えめで、爽やかな甘さが広がります。9月下旬～10月上旬に出回ります。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Pucci', 'Perfect for lunchboxes! A miniature apple designed to be eaten whole.', 'A cross between ''Sansa'' and ''Tsugaru'', this miniature apple is known for its thin skin that allows it to be eaten whole. It offers a refreshing sweetness with delicate tartness. It is typically available from late September to early October.', '探索', '蘋果品種', '長野原創品種', '信浓小布丁', '便當絕配！可帶皮整顆吃的小型蘋果', '「三茶 (Sansa)」與「津輕蘋果 (Tsugaru)」交配的極小蘋果。皮薄，可帶皮整顆食用是其特色。酸味低，帶有清涼的甜味。約在9月下旬至10月上旬上市。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%83%97%E3%83%83%E3%83%81.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-06-0018', 'manual', '知る', '栽培されている品種', '長野県生まれの品種', 'シナノドルチェ', '果汁たっぷり！甘みと酸味のコントラストが魅力', '「ゴールデンデリシャス」と「千秋」を交配。甘みと酸味がはっきりしていて、豊富な果汁とさわやかな風味が楽しめます。9月中旬から下旬に出回る少し大きめのりんごです。', 'Discover', 'Apple Varieties', 'Nagano-Bred Varieties', 'Shinano Dolce', 'Juicy and refreshing! The delightful contrast of sweetness and tartness is its charm.', 'A cross between ''Golden Delicious'' and ''Senshu''. With distinct sweetness and tartness, it offers abundant juice and a refreshing flavor. It is a slightly larger apple available from mid to late September.', '探索', '蘋果品種', '長野原創品種', '信浓多切', '多汁！甜味與酸味的對比是其魅力', '「金冠蘋果 (Golden Delicious)」與「千秋蘋果 (Senko)」交配。具有明顯的甜酸對比，果汁豐富，風味清爽。是9月中旬至下旬出現的略大蘋果。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B7%E3%83%8A%E3%83%8E%E3%83%89%E3%83%AB%E3%83%81%E3%82%A7.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-07-0011', 'manual', '知る', '栽培されている品種', '海外生まれのりんご', 'ブラムリー', 'イギリス発祥の「クッキングアップル」の王様', '強い酸味と加熱で溶けやすい果肉が特徴。パイやジャムなどに最適な料理用りんごの代表格です。飯綱町内の各農園が栽培のパイオニアです。', 'Discover', 'Apple Varieties', 'Foreign Varieties', 'Bramley', 'The King of ''Cooking Apples'' originating from the UK.', 'Characterized by its robust tartness and flesh that quickly softens when heated. It is the quintessential culinary apple, perfect for pies, jams, and more. Apple farms in Iizuna Town act as pioneers in its cultivation.', '探索', '蘋果品種', '海外原創品種', '布莱姆利', '源自英國的「烹飪用蘋果」之王', '強烈的酸味與加熱後容易融化的果肉是其特色。最適合用於製作蘋果派或果醬等料理的蘋果。飯綱町的蘋果農園是栽培這款品種的先驅。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%83%96%E3%83%A9%E3%83%A0%E3%83%AA%E3%83%BC.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO contents (id, type, l1, l2, l3_label, title, lead_text, body_text, l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en, l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw, image1, image2, image3, image4, image5, image6, homepage, related1_url, related1_title, related2_url, related2_title, ec_site, sns_instagram, sns_facebook, sns_x, sns_line, sns_tiktok, address, contact_form_url, contact_email, contact_phone, remarks, download_url, business_days, business_start, business_end, closed_days, business_remarks, start_date, end_date, start_time, end_time, fee, belongings, target_audience, organizer_name, organizer_contact, application_method, venue_remarks) VALUES
('02-04-07-0014', 'manual', '知る', '栽培されている品種', '海外生まれのりんご', 'グラニースミス', '欧米ではアップルパイの定番！鮮やかな緑色のクッキングアップル', 'オーストラリア生まれ。強めの酸味と硬めの果肉が特徴の緑りんごです。火を通しても風味が落ちないため、煮込み料理やスイーツ作りにぴったり。もちろん生食も楽しめます。', 'Discover', 'Apple Varieties', 'Foreign Varieties', 'Granny Smith', 'In Europe and America, it is a staple for apple pies! A vibrant green cooking apple.', 'Born in Australia, this vibrant green apple is known for its strong tartness and firm flesh. Its flavor holds up perfectly to heat, making it ideal for stews and baking. It can also be enjoyed fresh.', '探索', '蘋果品種', '海外原創品種', '澳洲青苹', '在歐美是蘋果派的必備食材！鮮綠色的烹飪用蘋果', '源自澳洲，綠色外觀，帶有強烈酸味與結實的果肉。由於加熱後風味不減，因此非常適合燉煮或製作甜點。生吃也很美味。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%82%B0%E3%83%A9%E3%83%8B%E3%83%BC%E3%82%B9%E3%83%9F%E3%82%B9.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-07-0024', 'manual', '知る', '栽培されている品種', '海外生まれのりんご', 'ピンクレディ', '甘みと酸味が引き立つオーストラリア生まれのブランドりんご', 'ピンクレディの正式品種名は「クリプスピンク」。甘みと酸味がはっきりしていて濃厚な味わいが楽しめます。日持ちも良く、華やかなピンク色が目を引きます。', 'Discover', 'Apple Varieties', 'Foreign Varieties', 'Pink Lady', 'A brand apple from Australia that highlights sweetness and tartness.', 'The official varietal name is ''Cripps Pink.'' It boasts a pronounced sweetness and tartness, offering a rich and satisfying flavor. With excellent shelf life and a noticeable pink hue, it demands attention.', '探索', '蘋果品種', '海外原創品種', '粉紅佳人', '源自澳洲，甜味與酸味突出的品牌蘋果', '粉紅佳人的正式品種名為「Cripps Pink」。甜味與酸味分明，風味濃厚。保存期長，華麗的粉紅色外觀十分搶眼。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%83%94%E3%83%B3%E3%82%AF%E3%83%AC%E3%83%87%E3%82%A3%E3%83%BC.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-08-0019', 'manual', '知る', '栽培されている品種', '赤果肉のりんご', 'ムーンルージュ', 'カットして驚き！月明かりのように黄色い果皮と赤い果肉', '「いろどり」と「ふじ」の交配から生まれた、珍しい「赤果肉りんご」。見た目は黄色ですが、切ってみると薄い赤色やきれいなピンク色の果肉が現れます。甘みが強く蜜も入りやすいのが特徴で、11月上旬が食べ頃です。長野県中野市で開発された品種です。', 'Discover', 'Apple Varieties', 'Red-fleshed Apples', 'Moon Rouge', 'A surprise inside! Yellow skin like moonlight and red flesh.', 'A crossbreed of ''Irodori'' and ''Fuji'', generating this rare red-fleshed apple. Though yellow on the outside, a light red or bright pink flesh reveals itself when cut. Strong sweetness and a high likelihood of honeycore mark its features. Perfect for eating around early November, it was developed in Nakano City, Nagano Prefecture.', '探索', '蘋果品種', '紅肉蘋果', '月影紅 (Moon Rouge)', '切開有驚喜！如月光般的黃色外皮與紅色果肉', '由「彩 (Irodori)」與「富士蘋果 (Fuji)」交配而成的稀有紅肉蘋果。外觀呈黃色，切開後果肉呈現淡紅色或漂亮的粉紅色。甜度高且容易結蜜，11月上旬是最佳品嚐期。由長野縣中野市開發的品種。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%83%A0%E3%83%BC%E3%83%B3%E3%83%AB%E3%83%BC%E3%82%B8%E3%83%A5.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-08-0020', 'manual', '知る', '栽培されている品種', '赤果肉のりんご', '炎舞（えんぶ）', '情熱的な赤色！皮から果肉まで鮮やかな赤に染まる新品種', '「いろどり」と「ふじ」の交配種。その名の通り、まるで炎が舞うように、皮から中の果肉まで鮮やかな赤に染まっています。甘みと酸味のバランスが良く、風味豊かな味わいが楽しめます。長野県中野市で開発されました。10月中旬～下旬が旬。', 'Discover', 'Apple Varieties', 'Red-fleshed Apples', 'Enbu', 'Passionate red! A new variety saturated in bright red from skin to flesh.', 'A cross of ''Irodori'' and ''Fuji''. Just like dancing flames, both its skin and inner flesh display an intense red. It provides a rich flavor with a harmonious blend of sweetness and tartness. Harvested from mid to late October, it was also developed in Nakano City, Nagano.', '探索', '蘋果品種', '紅肉蘋果', '炎舞 (Enbu)', '熱情的紅色！從裡到外都是鮮紅色的新品種', '「彩 (Irodori)」與「富士蘋果 (Fuji)」交配的品種。如同其名，它的紅就像是舞動的火焰，從皮到果肉都呈現鮮艷的紅色。甜味與酸味達到極佳平衡，風味豐富。長野縣中野市開發。10月中旬至下旬為最佳品嚐期。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E7%82%8E%E8%88%9E.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO contents (id, type, l1, l2, l3_label, title, lead_text, body_text, l1_en, l2_en, l3_label_en, title_en, lead_text_en, body_text_en, l1_tw, l2_tw, l3_label_tw, title_tw, lead_text_tw, body_text_tw, image1, image2, image3, image4, image5, image6, homepage, related1_url, related1_title, related2_url, related2_title, ec_site, sns_instagram, sns_facebook, sns_x, sns_line, sns_tiktok, address, contact_form_url, contact_email, contact_phone, remarks, download_url, business_days, business_start, business_end, closed_days, business_remarks, start_date, end_date, start_time, end_time, fee, belongings, target_audience, organizer_name, organizer_contact, application_method, venue_remarks) VALUES
('02-04-08-0021', 'manual', '知る', '栽培されている品種', '赤果肉のりんご', 'なかののきらめき', '皮は黄色、果肉はピンク色！新しい味わい', '「王林」と「いろどり」の交配種。見た目は黄緑色ですが、中は美しいピンク色の果肉が広がります！甘みと酸味があり、風味豊かで果汁もたっぷり。長野県中野市で開発され、11月上旬が旬です。', 'Discover', 'Apple Varieties', 'Red-fleshed Apples', 'Nakano no Kirameki', 'Yellow skin, pink flesh! A new flavor experience.', 'A crossbreed of ''Orin'' and ''Irodori'', showing yellowish-green skin with surprisingly beautiful pink flesh inside. It offers a balanced flavor of sweetness and acidity, with plenty of juice. Developed in Nakano City, Nagano, and peaking in early November.', '探索', '蘋果品種', '紅肉蘋果', '中野閃耀 (Nakano no Kirameki)', '外皮黃色，果肉粉紅色！嶄新的風味', '「王林蘋果 (Orin)」與「彩 (Irodori)」交配的品種。外觀呈黃綠色，但內部則是美麗的粉紅果肉！帶有甜味與酸味，風味豐富且充滿果汁。長野縣中野市開發，11月上旬為最佳品嚐期。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%81%AA%E3%81%8B%E3%81%AE%E3%81%AE%E3%81%8D%E3%82%89%E3%82%81%E3%81%8D.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-08-0026', 'manual', '知る', '栽培されている品種', '赤果肉のりんご', '冬彩華（とうさいか）', '11月に楽しめる！彩り豊かな赤果肉', '「ふじ」と「ピンクパール」などの交配種。果肉は美しいピンク色で、甘みと酸味のバランスが良いのが特徴です。11月上旬に出回る、彩り鮮やかなりんごです。', 'Discover', 'Apple Varieties', 'Red-fleshed Apples', 'Tosaika', 'Enjoy it in November! A brightly colored red-fleshed apple.', 'A cross of ''Fuji'' and ''Pink Pearl''. Its flesh boasts a gorgeous pink hue, offering a pleasant balance of sweetness and acidity. This vibrant apple appears in early November.', '探索', '蘋果品種', '紅肉蘋果', '冬彩華 (Tosaika)', '11月即可享用！色彩繽紛的紅肉蘋果', '「富士蘋果 (Fuji)」與「粉紅珍珠 (Pink Pearl)」交配的品種。果肉呈現美麗的粉紅色，甜味與酸味達到很好的平衡。是在11月上旬上市，色彩鮮豔的蘋果。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E5%86%AC%E5%BD%A9%E8%8F%AF.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('02-04-09-0028', 'manual', '知る', '栽培されている品種', 'その他の品種', 'ぐんま名月（めいげつ）', '蜜が入りやすく、濃厚な甘みが特徴の黄色いりんご', '「あかぎ」と「ふじ」の交配種。黄色い果皮ですが、日光に当たる部分がオレンジ色に色づくのが特徴。蜜が入りやすく、酸味が少なくて強い甘みが楽しめます。11月上旬が旬です。', 'Discover', 'Apple Varieties', 'Other Varieties', 'Gunma Meigetsu', 'A yellow apple characterized by its tendency to develop honeycore and intense sweetness.', 'A cross between ''Akagi'' and ''Fuji''. Despite its yellow skin, areas exposed to sunlight blush orange. It easily forms a honeycore, providing a potent sweetness with minimal acidity. Enjoy it in early November.', '探索', '蘋果品種', '其他品種', '群馬名月 (Gunma Meigetsu)', '容易結蜜，具有濃厚甜味的黃色蘋果', '「赤城 (Akagi)」與「富士蘋果 (Fuji)」交配的品種。黃色的果皮，但受到陽光照射的部分會染成橙色。容易結出蜜心，酸味較低，可充分享受其強烈的甜味。11月上旬為產季。', 'https://appletown-iizuna.s3.ap-northeast-1.amazonaws.com/apples/images/%E3%81%90%E3%82%93%E3%81%BE%E5%90%8D%E6%9C%88.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('14-19-20-0013', 'manual', '発信する', '記事・コラム', 'ふるさと納税返礼品', '11月：飯綱町からのお歳暮', 'りんご好きの方へ贈る、感謝の気持ち', 'ふるさと納税で、飯綱町の美味しいりんごを「お歳暮」としてお届けしませんか？長野県の豊かな自然の中で育った、農家直送の甘くてシャキシャキのりんごは、大切な方への贈り物に最適です', 'Share & Connect', 'Articles & Columns', 'Hometown Tax Return Gifts', 'November: Year-end Gift from Iizuna Town', 'A token of gratitude for apple lovers.', 'Why not send delicious Iizuna apples as a year-end gift through the hometown tax system? Grown in the abundant nature of Nagano Prefecture and delivered directly from farmers, our sweet, crisp apples make the perfect gift for someone special.', '傳播與連結', '文章與專欄', '故鄉納稅回饋品', '11月：來自飯綱町的歲末禮物', '送給喜愛蘋果的您，表達感謝之意', '透過故鄉納稅，將飯綱町美味的蘋果作為「歲暮」送禮吧？在長野縣豐饒自然中孕育，由農家直送的香甜酥脆蘋果，是送給重要之人的最佳選擇。', 'https://s3-ap-northeast-1.amazonaws.com/s3.peraichi.com/userData/cadd36d5-015f-4440-aa3c-b426c32c22a0/img/56bd31a0-8326-013e-1081-0a58a9feac02/furusato_4.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

